export enum ActionTypes {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS",
    REGISTER_SUCCESS = "REGISTER SUCCESS",
    LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS",
    LOG_OUT_FAILURE = "LOG_OUT_FAILURE",
    USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
    USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE",
    USER_PHOTOS_RETRIEVED_SUCCESS = "USER_PHOTOS_RETRIEVED_SUCCESS",
    USER_PHOTOS_RETRIEVED_FAILURE = "USER_PHOTOS_RETRIEVED_FAILURE",
    REDIRECT = "REDIRECT",
    CLEAR_HISTORY = "CLEAR_HISTORY"
}
